USE [master]
GO

/****** Object:  Database [CARWASH]    Script Date: 28.12.2024 20:44:54 ******/
CREATE DATABASE [CARWASH]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CARWASH', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLARİF\MSSQL\DATA\CARWASH.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CARWASH_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLARİF\MSSQL\DATA\CARWASH_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CARWASH].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CARWASH] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CARWASH] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CARWASH] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CARWASH] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CARWASH] SET ARITHABORT OFF 
GO

ALTER DATABASE [CARWASH] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CARWASH] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CARWASH] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CARWASH] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CARWASH] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CARWASH] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CARWASH] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CARWASH] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CARWASH] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CARWASH] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CARWASH] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CARWASH] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CARWASH] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CARWASH] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CARWASH] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CARWASH] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CARWASH] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CARWASH] SET RECOVERY FULL 
GO

ALTER DATABASE [CARWASH] SET  MULTI_USER 
GO

ALTER DATABASE [CARWASH] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CARWASH] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CARWASH] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CARWASH] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CARWASH] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CARWASH] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CARWASH] SET QUERY_STORE = ON
GO

ALTER DATABASE [CARWASH] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [CARWASH] SET  READ_WRITE 
GO

